# Generated by Django 4.2.17 on 2025-02-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('user_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepicture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('workPosition', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('maritalStatus', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('maritalstatus', models.CharField(max_length=20)),
                ('profilePicture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('timetreatment', models.CharField(max_length=100)),
                ('transactiondetails', models.CharField(max_length=100)),
                ('medicineused', models.TextField(blank=True, default='N/A')),
                ('bpbefore', models.CharField(max_length=50)),
                ('bpafter', models.CharField(max_length=50)),
                ('weightbefore', models.CharField(max_length=50)),
                ('weightafter', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('pulsebefore', models.CharField(max_length=50)),
                ('pulseafter', models.CharField(max_length=50)),
                ('generalremarks', models.TextField(blank=True, default='N/A')),
                ('attendingstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('contactnumber', models.CharField(max_length=50)),
                ('requestdate', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=50)),
                ('requestpurpose', models.CharField(choices=[('medicine ', 'medicine '), ('medicalabstract', 'medicalabstract '), ('others', 'others')], default='medicine', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff')),
            ],
        ),
    ]
