# Generated by Django 4.2.17 on 2025-02-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-queue', 'in-queue'), ('completed', 'completed'), ('missed', 'missed'), ('cancelled', 'cancelled')], default='Pending', max_length=50)),
                ('type', models.CharField(choices=[('consultation ', 'consultation '), ('certificates', 'certificates '), ('others', 'others')], default='none', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_or_employee_no', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('campus', models.CharField(max_length=100)),
                ('patient_type', models.CharField(default='student', max_length=100)),
                ('college_office', models.CharField(max_length=100)),
                ('course_designation', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_relation', models.CharField(max_length=15)),
                ('bloodtype', models.CharField(max_length=15)),
                ('allergies', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=15)),
                ('sex', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('profilePicture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueueManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Certificates', 'Certificates'), ('Others', 'Others')], default='Consultation', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('user_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepicture', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('specialization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Served', 'Served'), ('Skipped', 'Skipped'), ('in', 'in')], default='Pending', max_length=10)),
                ('ticket_type', models.CharField(choices=[('walk-in', 'Walk-in'), ('appointment', 'Appointment')], default='walk-in', max_length=15)),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Certificates', 'Certificates'), ('Others', 'Others')], default='Consultation', max_length=20)),
                ('is_priority', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic_python.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
                ('qmid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.queuemanagement')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user_level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.role'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('transactiondetails', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('heart_rate', models.CharField(max_length=50)),
                ('respiratory_rate', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('bloodpressure', models.CharField(max_length=50)),
                ('painscale', models.CharField(max_length=50)),
                ('othersymptoms', models.CharField(max_length=255)),
                ('initialdiagnosis', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=50)),
                ('attendingstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff'),
        ),
    ]
