# Generated by Django 5.1.6 on 2025-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='maritalStatus',
            new_name='maritalstatus',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='workPosition',
            new_name='workposition',
        ),
        migrations.AlterField(
            model_name='staff',
            name='birthday',
            field=models.DateField(),
        ),
    ]
