# Generated by Django 5.1.4 on 2024-12-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Served', 'Served'), ('Skipped', 'Skipped'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('ticket_type', models.CharField(choices=[('walk-in', 'Walk-in'), ('appointment', 'Appointment')], default='walk-in', max_length=15)),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Certificates', 'Certificates'), ('Others', 'Others')], default='Consultation', max_length=20)),
                ('is_priority', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic_python.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
            ],
        ),
    ]
