# Generated by Django 5.1.6 on 2025-02-12 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0002_rename_maritalstatus_staff_maritalstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
