# Generated by Django 5.1.4 on 2024-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0003_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('pending', 'pending'), ('in-queue', 'in-queue'), ('completed', 'completed'), ('missed', 'missed'), ('cancelled', 'cancelled')], default='Pending', max_length=50),
        ),
    ]
