# Generated by Django 5.1.6 on 2025-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0003_medicalrecord_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='requestpurpose',
            field=models.CharField(choices=[('medicine ', 'medicine '), ('medicalabstract', 'medicalabstract '), ('others', 'others')], default='medicine', max_length=100),
        ),
    ]
