# Generated by Django 5.1.6 on 2025-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0004_alter_appointment_requestpurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='requestpurpose',
            field=models.CharField(default='medicine', max_length=100),
        ),
    ]
