# Generated by Django 5.1.6 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0005_alter_appointment_requestpurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to='uploads/'),
        ),
    ]
