# Generated by Django 5.1.6 on 2025-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0007_alter_patient_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to='uploads/'),
        ),
    ]
