# Generated by Django 4.2.17 on 2024-12-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0007_remove_role_permission_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
