# Generated by Django 4.2.17 on 2024-12-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0008_patient_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
