# Generated by Django 4.2.17 on 2024-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0009_rename_is_delete_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='student_or_employee_no',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
