# Generated by Django 4.2.17 on 2024-12-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0010_patient_student_or_employee_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
