# Generated by Django 5.1.6 on 2025-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0010_alter_patient_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='transactiondetails',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='transactiontype',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profilepicture',
        ),
        migrations.AddField(
            model_name='staff',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to='upload_to/'),
        ),
    ]
