# Generated by Django 4.2.17 on 2024-12-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0011_patient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
