# Generated by Django 4.2.17 on 2025-03-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, default='N/A'),
        ),
    ]
