# Generated by Django 4.2.17 on 2024-12-16 12:36

import clinic_python.models.patient_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0014_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=clinic_python.models.patient_model.upload_to, verbose_name='Image'),
        ),
    ]
