# Generated by Django 4.2.17 on 2024-12-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0015_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
