# Generated by Django 4.2.17 on 2024-12-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0016_rename_profile_picture_patient_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_date', models.DateField()),
                ('purpose', models.CharField(choices=[('consultation ', 'consultation '), ('certificates', 'certificates '), ('others', 'others')], default='none', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in-queue', 'in-queue'), ('completed', 'completed'), ('missed', 'missed'), ('cancelled', 'cancelled')], default='Pending', max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff')),
            ],
        ),
    ]
