# Generated by Django 4.2.17 on 2024-12-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0018_queuemanagement_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='student_or_employee_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queuemanagement',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
