# Generated by Django 4.2.17 on 2024-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0020_alter_patient_student_or_employee_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='student_or_employee_no',
            field=models.CharField(max_length=50),
        ),
    ]
