# Generated by Django 4.2.17 on 2024-12-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0021_alter_patient_student_or_employee_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('transactiondetails', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('hr', models.CharField(max_length=50)),
                ('rr', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('bloodpressure', models.CharField(max_length=50)),
                ('painscale', models.CharField(max_length=50)),
                ('othersymptoms', models.CharField(max_length=255)),
                ('initialdiagnosis', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('attendingstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.staff')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_python.patient')),
            ],
        ),
    ]
