# Generated by Django 4.2.17 on 2024-12-23 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0022_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='qmid',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.CharField(default=21, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('consultation ', 'consultation '), ('certificates', 'certificates '), ('others', 'others')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='student_or_employee_no',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='QueueManagement',
        ),
    ]
