# Generated by Django 4.2.17 on 2024-12-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0024_queuemanagement_remove_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_number',
            field=models.CharField(max_length=5),
        ),
    ]
