# Generated by Django 4.2.17 on 2024-12-23 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0025_alter_queue_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
