# Generated by Django 4.2.17 on 2024-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0027_staff_is_deleted_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Served', 'Served'), ('Skipped', 'Skipped'), ('in', 'in')], default='Pending', max_length=10),
        ),
    ]
