# Generated by Django 4.2.17 on 2024-12-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_python', '0030_patient_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profilepicture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
